os.execute("pdflatex report.tex")
os.execute("bibtex report.aux")
os.execute("pdflatex report.tex")
os.execute("pdflatex report.tex")
os.execute("mkdir output")
os.execute("move report.pdf output")
os.execute("del *.out")
os.execute("del *.bbl")
os.execute("del *.blg")
os.execute("del *.log")
os.execute("del *.aux")
